name: Database Migration

on:
  push:
    branches: [ "main" ]

jobs:
  database-migration:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
      with:
        php-version: '8.1'

    - name: Set Up Environment Variables
      run: |
        echo "APP_ENV=prod" >> $GITHUB_ENV
        echo "DATABASE_URL='${{ secrets.DATABASE_URL }}'" >> $GITHUB_ENV

    - name: Dump .env
      run: |
        rm -f .env
        echo "APP_ENV=prod" >> .env
        echo "DATABASE_URL='${{ secrets.DATABASE_URL }}'" >> .env

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install Composer
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --no-dev --optimize-autoloader

    - name: Database Migrations
      run: php bin/console doctrine:migrations:migrate --no-interaction --all-or-nothing
